### ISSUE TITLE
v1.0 missing page and some images

### ISSUE THREAD

**Issue by wangxr011235** [manjurulhoque/django-social-network#27]
Not Found: /timeline-friends.html
Not Found: /notifications.html

**Comment by techrajdeep** [comment]
Hey @manjurulhoque , can I work on this?

**Comment by manjurulhoque** [comment]
> Hey @manjurulhoque , can I work on this?

Yes, if possible.

**Comment by techrajdeep** [comment]
can you explain the requirement a bit more..and assign it to me
