### ISSUE TITLE
Update readme with new version's screenshot

### ISSUE THREAD

**Issue by manjurulhoque** [manjurulhoque/django-social-network#29]

**Comment by divyamojas** [comment]
Hey @manjurulhoque please assign this to me. I want to work on this.

**Comment by manjurulhoque** [comment]
> Hey @manjurulhoque please assign this to me. I want to work on this.

Assigned to you.

**Comment by divyamojas** [comment]
Hey @manjurulhoque, in order to take screenshots for the live chatting page I need some users. When I run the current project, it shows "Add friends to chat". So, is there any database available for me to use?

**Comment by manjurulhoque** [comment]
You have 'social.sqlite3' database in the repo.

**Comment by 8bitaby** [comment]
Hey  @manjurulhoque. Can you please assign this to me. I want to contribute.

**Comment by manjurulhoque** [comment]
> Hey  @manjurulhoque. Can you please assign this to me. I want to contribute. 

Assigned to you.
